before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kASvUneZN+ZYuDt3XjS5HFiiJYnc8PdOP84XruLUF4z0wiGQXfgcHQZDa5K/8HSIioJodh/lRl71HbGsl3X/YDw3NC4dEofv84LRbNfVIyeKZTTnP6r3n2T6fx7qEJyRRZyWLNzbut3Fz6hRVHD/UhN7E8bg58hnZQoVd2KddjEPYmYWsA1T/LimsyFGC4FsrJ2GHwmzOWSrLj8lMTD3d88bfYPgYWzvRk31I316SA5rKrBOzOYMUPWW9zojla6yJD119wQW1PLx4zK+oVvEDS29PM30Me1OBqB7d97/3hrnYvPBeR0QeLglNr5P3LV1jZuWbZmEY8zqloWc/EQJc+PRT3Sye1gaheI0wOQqK9rZ1HmOlQLS3n72bYfQ7HWT+vqQs0CRfJV79IWtFwe7blXYX3HxKUaJZa/lMYie6/zzPIp1S/MpGXSVcvhtqjsU+4RMmx6rdoO3sgkI8DT47ObgZY9qvs4IZDg0qXBbPRlgDML7xF8Nlkd4CZiqGs2Nv/oN0GH4WNMK8aT6FddMTR4ndd0Rp9/x2UsmQdOHAV3ur4LtbqXTDKPipW/5fhcxlesHtv5Ufb9TEMcmpajOFckKCewMZMemHm6hevh5pz2CuJuBSJ/KNSyIpMGrG7fAShnGblqn+Zs3HBtVh5a/FMlRDFQE2/8mIMTqkub/vKs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
